version: '3'

services:
  tgi:
    image: ghcr.io/huggingface/text-generation-inference:1.2.0
    ports:
      - 3000:3000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              count: all
    volumes:
      - ./data:/data
    environment:
      MODEL_ID: TheBloke/zephyr-7B-beta-AWQ
      QUANTIZE: awq
      HOSTNAME: 0.0.0.0
      PORT: 3000
      MAX_INPUT_LENGTH: 2048
      MAX_TOTAL_TOKENS: 4096
  tei:
    image: ghcr.io/huggingface/text-embeddings-inference:latest
    ports:
      - 3001:3001
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              count: all
    volumes:
      - ./data:/data
    environment:
      MODEL_ID: BAAI/bge-large-en-v1.5
      HOSTNAME: 0.0.0.0
      PORT: 3001
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./qdrant:/qdrant/storage:z
